version: '3'

services:
  app:
    build:
      context: ./
      dockerfile: dockerfile.app
    working_dir: /var/www
    volumes:
      - .:/var/www
    depends_on:
      - memcached

  web:
    build:
      context: ./
      dockerfile: dockerfile.web
    working_dir: /var/www
    volumes:
      - .:/var/www
    ports:
      - 8000:80
    depends_on:
      - app
      - memcached

  memcached:
    image: memcached
    ports:
      - 11211:11211
    env_file:
      - .env

